[LV-234] Static patches
lunalabsltd/HarmonyX pull request #1
Opened 2020-09-15 10:07 UTC by AlexandrMatveev

2020-09-22 10:22 UTC, stepan-beresnev requested changes

2020-09-22 10:22 UTC, stepan-beresnev commented on Harmony/Internal/Patching/Static/AOT/AOTPatchContext.cs
> +            del.Name = $"{method.ReturnType.Name}_Delegate_{methodParameters.Join(ParameterName, "_")}_{_signatureToDelegate.Count}";
And here too, can we please make sure that all custom generated fields have some names including "harmony" so we can easily see, which methods are ours.

2020-09-22 10:22 UTC, stepan-beresnev commented on Harmony/Internal/Patching/Static/AOT/AOTPatchContext.cs
> +                    name = $"ref_{str.Remove(str.Length - 1)}";
Why remove the last symbol?

2020-09-25 15:56 UTC, AlexandrMatveev commented on Harmony/Internal/Patching/Static/AOT/DelegateBuilder.cs
> +            constructor.ImplAttributes = MethodImplAttributes.Runtime;
![image](https://user-images.githubusercontent.com/50839620/94289064-d729b700-ff60-11ea-93d8-81699ede3f5a.png)

2020-09-25 16:03 UTC, AlexandrMatveev commented on Harmony/Internal/Patching/Static/AOT/DelegateBuilder.cs
> +            constructor.ImplAttributes = MethodImplAttributes.Runtime;
It is like https://docs.microsoft.com/en-us/dotnet/api/system.runtime.compilerservices.methodimploptions?view=netframework-4.5

2020-10-05 12:19 UTC, AlexandrMatveev commented on Harmony/Internal/Patching/Static/AOT/FakeMethod.cs
> +            for (var i = 0; i < parameters.Length; i++)
Parameter .ctor needs method instance, so i push empty parameter array in type .ctor and then fill it with parameters

2020-10-12 11:38 UTC, closed without merging